namu/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("id/", views.redirect_to_index, name="redirectToIndex"),
    path("id/<int:user_id>/", views.redirect_to_buy, name="redirectToBuy"),
    path("id/<int:user_id>/buy", views.Buy.as_view(), name="buy"),
    path("id/<int:user_id>/topup", views.Topup.as_view(), name="topup"),
    path("id/<int:user_id>/revert", views.revert_previous_transaction, name="revert"),
    path("products/", views.Products.as_view(), name="products"),
    path("stats/", views.statistics, name="stats"),
]

namu/models.py
from decimal import *

from django.db import models
from django.db.models import Sum
from django.urls import reverse


class Namuseta(models.Model):
    name = models.CharField(max_length=100)
    mobilepay = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)


class User(models.Model):
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("topup", kwargs={"user_id": self.pk})

    def account_balance(self):
        t = Transaction.objects.filter(user=self).aggregate(sum=Sum("price"))
        t_sum = t["sum"] or Decimal(0.00)
        d = Deposit.objects.filter(user=self).aggregate(sum=Sum("amount"))
        d_sum = d["sum"] or Decimal(0.00)
        balance = round(d_sum - t_sum, 2)
        return balance


class Product(models.Model):
    class Meta:
        ordering = ["name"]

    CATEGORY_OPTIONS = (
        ("z", "Freezer"),
        ("f", "Fridge"),
        ("c", "Cabinet"),
    )

    name = models.CharField(max_length=100)
    category = models.CharField(max_length=1, choices=CATEGORY_OPTIONS, default="c")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    cost = models.DecimalField(max_digits=5, decimal_places=2)
    picture = models.ImageField(upload_to="namukilke/products")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def inventory_level(self):
        t_sum = Transaction.objects.filter(product=self).count()
        r = Restock.objects.filter(product=self).aggregate(sum=Sum("quantity"))
        r_sum = r["sum"] or 0
        inv = r_sum - t_sum
        return inv


class Transaction(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    cost = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S")


class Deposit(models.Model):
    PAYMENT_METHOD_OPTIONS = (
        ("c", "Cash"),
        ("m", "MobilePay"),
        ("r", "Refund"),
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    payment_method = models.CharField(
        max_length=1, choices=PAYMENT_METHOD_OPTIONS, default="c",
    )

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S")


class Restock(models.Model):
    RESTOCK_TYPES = (
        ("s", "Stock"),
        ("r", "Refund"),
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    type = models.CharField(max_length=1, choices=RESTOCK_TYPES, default="s",)

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S")


class Feedback(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.title

namu/views.py
import json
from datetime import datetime
from decimal import *

from django.contrib import messages
from django.db.models import Count, Q, Sum
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import Deposit, Namuseta, Product, Restock, Transaction, User


def redirect_to_buy(request, user_id):
    return redirect("./buy")


def redirect_to_index(request):
    return redirect("../")


class Index(ListView):
    """Render a list of users for selection"""

    model = User
    template_name = "namu/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.filter(is_active=True)
        user_names = {"{} - {}".format(u.id, u.name): None for u in users}
        context["user_autocomplete"] = json.dumps(user_names)
        n = Namuseta.objects.get(pk=1)
        context["namuseta"] = n
        return context

    # TODO: form validation: throw error if name > 100 char & warning if name is not unique. current FieldError not working
    def post(self, *args, **kwargs):
        new_name = self.request.POST["name"]
        try:
            u = User.objects.create(name=new_name)
            u.save()
            messages.success(self.request, "Account " + u.name + " created!")
        except User.FieldError:
            messages.warning(self.request, "Error - invalid name!")
        return HttpResponseRedirect(reverse("topup", kwargs={"user_id": u.id}))


class Products(ListView):
    """ List product details & sales numbers. A nice-to-have feature.
        Additions and modifications through django admin or separate log-in to prevent tampering"""

    model = Product
    template_name = "namu/products.html"


class Buy(ListView):
    """Display information about user & allow them to purchase products"""

    model = Product
    template_name = "namu/buy.html"

    def post(self, *args, **kwargs):
        """Buy a given product"""
        try:
            u = User.objects.get(pk=self.kwargs["user_id"])
        except User.DoesNotExist:
            raise Http404("Account does not exist")
        try:
            p = Product.objects.get(pk=self.request.POST["product_id"])
        except Product.DoesNotExist:
            raise Http404("Product does not exist")

        bal = u.account_balance()
        if bal >= p.price:
            t = Transaction(product=p, user=u, price=p.price, cost=p.cost)
            t.save()
            messages.info(self.request, p.name + " bought!")
        else:
            messages.error(self.request, "Error - not enough funds!")
        return HttpResponseRedirect(reverse("buy", kwargs={"user_id": u.id}))

    def get_queryset(self):
        u = User.objects.get(pk=self.kwargs["user_id"])
        if Transaction.objects.filter(user=u).exists():
            user_transaction = Count("transaction", filter=Q(transaction__user=u))
            products = Product.objects.annotate(buy_count=user_transaction)
            active_products = products.filter(is_active=True).order_by("-buy_count")
        else:
            active_products = Product.objects.filter(is_active=True)
        return active_products

    def get_context_data(self, *args, **kwargs):
        context = super(Buy, self).get_context_data(**kwargs)
        try:
            u = User.objects.get(pk=self.kwargs["user_id"])
        except User.DoesNotExist:
            raise Http404("Account does not exist")
        context["user"] = u
        context["balance"] = u.account_balance()
        n = Namuseta.objects.get(pk=1)
        context["namuseta"] = n
        return context


def revert_previous_transaction(request, **kwargs):
    """Create deposit and restock objects to revert previous transaction"""
    if request.method == "POST":
        try:
            u = User.objects.get(pk=kwargs["user_id"])
        except User.DoesNotExist:
            raise Http404("Account does not exist")
        t = Transaction.objects.filter(user=u).last()
        if t:
            d = Deposit(user=u, amount=t.price, payment_method="r")
            r = Restock(product=t.product, quantity=1, type="r")
            d.save()
            r.save()
            messages.success(request, r.product.name + " refunded")
        else:
            messages.warning(request, "Error - No transactions to revert")
        return HttpResponseRedirect(reverse("buy", kwargs={"user_id": u.id}))


class Topup(DetailView):
    """Let user make a deposit."""

    model = User
    template_name = "namu/topup.html"
    context_object_name = "user"
    pk_url_kwarg = "user_id"

    def get_context_data(self, *args, **kwargs):
        context = super(Topup, self).get_context_data(**kwargs)
        context["account_balance"] = self.get_object().account_balance()
        context["cash_units"] = [50, 20, 10, 5, 2, 1, 0.50, 0.20, 0.10, 0.05]
        n = Namuseta.objects.get(pk=1)
        context["namuseta"] = n
        return context

    def post(self, *args, **kwargs):
        u = self.get_object()
        d = Deposit(
            user=u,
            amount=self.request.POST["amount"],
            payment_method=self.request.POST["payment_method"],
        )
        d.save()
        messages.success(self.request, d.amount + " euros added to your account!")
        return HttpResponseRedirect(reverse("buy", kwargs={"user_id": u.id}))


def statistics(request, **kwargs):
    """Show basic statistics of topups and purchases."""
    if request.method == "GET":

        start = request.GET.get("start", "2018-09-01")
        end = request.GET.get("end", datetime.now().strftime("%Y-%m-%d"))

        # Change in sales, refunds, deposits, and balances
        sales = Transaction.objects.filter(
            timestamp__gte=start, timestamp__lt=end
        ).aggregate(price=Sum("price"), cost=Sum("cost"))
        sales_price = round(sales["price"] or Decimal(0.00), 2)
        sales_cost = round(sales["cost"] or Decimal(0.00), 2)

        refunds = Deposit.objects.filter(
            payment_method="r", timestamp__gte=start, timestamp__lt=end
        ).aggregate(amount=Sum("amount"))
        refunds = round(refunds["amount"] or Decimal(0.00), 2)

        deposits = Deposit.objects.filter(
            Q(payment_method="m") | Q(payment_method="c"),
            timestamp__gte=start,
            timestamp__lt=end,
        ).aggregate(amount=Sum("amount"))
        deposits = round(deposits["amount"] or Decimal(0.00), 2)

        net_sales = sales_price - refunds

        # TODO: Margin should be added " + refunds_cost" in order to be accurate but this is currently not stored in the database
        est_margin = sales_price - refunds - sales_cost

        balances_change = deposits + refunds - sales_price

        # Balances at start
        sales_until_start = Transaction.objects.filter(timestamp__lt=start).aggregate(
            price=Sum("price"), cost=Sum("cost")
        )
        sales_price_until_start = round(sales_until_start["price"] or Decimal(0.00), 2)

        refunds_until_start = Deposit.objects.filter(
            payment_method="r", timestamp__lt=start
        ).aggregate(amount=Sum("amount"))
        refunds_until_start = round(refunds_until_start["amount"] or Decimal(0.00), 2)

        deposits_until_start = Deposit.objects.filter(
            Q(payment_method="m") | Q(payment_method="c"), timestamp__lt=start
        ).aggregate(amount=Sum("amount"))
        deposits_until_start = round(deposits_until_start["amount"] or Decimal(0.00), 2)

        balances_at_start = (
            deposits_until_start + refunds_until_start - sales_price_until_start
        )
        balances_at_end = balances_at_start + balances_change

        # TODO: Inventory values and losses
        # TODO: multiply quantity with price to get restocks. Should store the cost at the time of restock
        # restock = Restock.objects.filter(type='s').aggregate(restock_price=Sum('product__price'), restock_cost=Sum('product__cost'))

        context = {
            "date_start": start,
            "date_end": end,
            "sales_price": sales_price,
            "sales_cost": sales_cost,
            "refunds": refunds,
            "net_sales": net_sales,
            "est_margin": est_margin,
            "deposits": deposits,
            "balances_start": balances_at_start,
            "balances_end": balances_at_end,
            "balances_change": balances_change,
        }

        return render(request, "namu/stats.html", context)
    pass

namu/templates/namu/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
  <title>Namukilke</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=800px, user-scalable=no" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/namu.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <main>
    <div class="container section">
      <a href="https://www.fiksuruoka.fi/" target="_blank">
        <img src="{% static 'img/fiksuruoka.png' %}" width="100px"/>
      </a>
      <a class="modal-trigger" href="#help-modal">
        <i class="material-icons right small black-text">live_help</i>
      </a>
    </div>
    <div class="container center-align">
      {% block body %}

      {% endblock body %}

      <div id="help-modal" class="modal">
        <div class="modal-content container">
          <h5>Instructions</h5>
          <p class="left-align">
            1. Each human should have only one account in Namukilke.
          </p>
          <p class="left-align">
            2. Account balance may never be negative. Add funds to you account before making a purchase.
          </p>
          <p class="left-align">
            3. Account may be deemed inactive if there has not had any activity for two years. Balances of inactive accounts may be wiped and the money used for common good (e.g. free ice cream at the guild room).
          </p>
          <p>
            Send any feedback or product requests to Namusetä {{ namuseta.name }} at {{ namuseta.contact }}.
          </p>
          <button class="modal-close waves-effect waves-light btn">Close</button>
        </div>
      </div>

      <div id="error-modal" class="modal">
        <div class="modal-content">
          <h4>Not enough funds!</h4>
          <p>Add more funds to your account and try again.</p>
          <button class="modal-close waves-effect waves-light btn">OK</button>
        </div>
      </div>
    </div>
  </main>
  {% comment %}
    Show Success/Warning messages.
    Throw an error modal instead if not enough funds.
    Use tag 'info' for purchases and display UNDO button.
  {% endcomment %}
  <script>
    $(document).ready(function() {
      $("#help-modal").modal({
          displayLength: 6000
      });
    });

    {% if messages %}
      {% for message in messages %}

        var toastTag = '{{ message.tags }}';
        var toastClass = 'toast-' + toastTag;

        if (toastTag === 'info') {
          var toastHTML = '<span>{{ message }}</span><form action={% url "revert" user.id %} method="post">{% csrf_token %}<button class="btn-flat toast-action">Undo</button></form>';
        } else {
          var toastHTML = '{{ message }}';
        };

        if (toastTag === 'error') {
          $('#error-modal').modal();
          $('#error-modal').modal('open');
        } else {
          window.onload = function(){
            M.toast({
              html: toastHTML,
              classes: toastClass
            });
          };
        };

      {% endfor %}
    {% endif %}
  </script>

</body>
</html>

namu/templates/namu/buy.html
{% extends 'namu/base.html' %}

{% load static %}

{% block body %}
  <div class="row section">
    <div class="col s6 offset-s3">
      <h3>Namukilke</h3>
      <div class="divider"></div>
      <h5>{{ user.name }}</h5>
      <h6>Account balance: {{ balance }} €</h6>
    </div>
  </div>
  <div class="row">
    <div class="col s6 right-align">
      <a class="waves-effect waves-light btn-large" href={% url "index" %}><span>Sign out</span></a>
    </div>
    <div class="col s6 left-align">
      <a class="waves-effect waves-light btn-large" href={% url "topup" user.id %}><span>Add funds</span></a>
    </div>
  </div>
  <br>
  <div class="divider"></div>

  <div class="row section">
    <div class="col s12">
      <h5>Grab some food</h5>
    </div>
  </div>

  <div class="row product-list">
    {% for product in product_list %}
        <div class="card medium">
          <div class="card-image">
            <a href="#">
              <img src="{{ product.picture.url }}" onclick="document.getElementById('buy-{{ forloop.counter }}').submit();"/>
            </a>
          </div>
          <div class="card-content">
            <span class="card-title">{{ product.name }}</span>
            <span class="card-title">{{ product.price }} €</span>
            <p>{{ product.inventory_level }} left in stock</p>
          </div>
          <div class="card-action">
            <form id="buy-{{ forloop.counter }}" action={% url "buy" user.id %} method="post">
              {% csrf_token %}
              <input name="product_id" type="hidden" value="{{ product.id }}">
              <button class="btn waves-effect waves-light" type="submit">Buy</button>
            </form>
          </div>
        </div>
    {% endfor %}
  </div>
  <div class="divider"></div>

{% endblock body %}

namu/templates/namu/deposit.html
<!-- This is the page for increasing user account balance -->

Money money moneyyy, MONEYYY!

namu/templates/namu/index.html
{% extends 'namu/base.html' %}

{% block body %}

  <div class="row section">
    <div class="col s6 offset-s3">
      <h3>Namukilke</h3>
      <div class="divider"></div>
    </div>
  </div>
  <div class="row section">
    <div class="col s6 offset-s3">
      <h5 class="section">Choose an existing user</h5>
      <div class="input-field">
        <i class="material-icons prefix">person</i>
        <input type="text" id="user-name" class="autocomplete">
        <label for="user-name">Search with name or user id</label>
      </div>
    </div>
  </div>
  <div class="divider"></div>

  <div class="row section">
    <form class="col s6 offset-s3" action={% url "index" %} method="post">
      <h5 class="section">Create a new user</h5>
      <div class="row">
        {% csrf_token %}
        <div class="input-field">
          <i class="material-icons prefix">person_add</i>
          <input type="text" name="name" id="name" required>
          <label for="name">Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <button class="btn btn-large waves-effect waves-light" type="submit"><span>Create new user</span></button>
        </div>
      </div>
    </form>
  </div>
  <div class="divider"></div>
  <div class="row section center-align">
    <a class="btn waves-effect waves-light" href={% url "stats" %}><span>Stats</span></a>
  </div>

  <script>
    var user_data = {{ user_autocomplete|safe }}
    $(document).ready(function(){
      $('input.autocomplete').autocomplete({
        data: user_data,
        onAutocomplete: function(){
          var name = $("#user-name").val();
          var n = name.indexOf("-");
          var user_id = name.slice(0, n - 1);
          location.assign(location + "id/" + user_id)
        },
      });
    });

  </script>

{% endblock body %}

namu/templates/namu/products.html
List product details and sales numbers for admin purposes. A nice to have feature to be done in the future.

namu/templates/namu/stats.html
{% extends 'namu/base.html' %}

{% block body %}

  <h3>Statistacs</h3>
  <p>Timestamps in UTC</p>
  <form id="date_form" action="{% url "stats" %}" method="get">
    <div class="row">
      <div class="col s3 offset-s3">
        Start date <input type="text" name="start" class="datepicker center-align" value="{{ date_start }}">
      </div>
      <div class="col s3">
        End date <input type="text" name="end" class="datepicker center-align" value="{{ date_end }}">
      </div>
    </div>
    <div class="row center-align">
      <button class="btn waves-effect waves-light" type="submit"><span>Refresh</span></button>
    </div>
  </form>
  <div class="row section">
    <div class="col s6 right-align">Gross Sales:</div>
    <div class="col s6 left-align">{{ sales_price }}</div>

    <div class="col s6 right-align">Refunds:</div>
    <div class="col s6 left-align">{{ refunds }}</div>

    <div class="col s6 right-align">Net Sales:</div>
    <div class="col s6 left-align">{{ net_sales }}</div>

    <div class="col s6 right-align">Estimated COGS:</div>
    <div class="col s6 left-align">{{ sales_cost }}</div>

    <div class="col s6 right-align">Estimated Sales Margin:</div>
    <div class="col s6 left-align">{{ est_margin }}</div>
  </div>
  <div class="row section">
    <div class="col s6 right-align">Balances {{ date_start }}:</div>
    <div class="col s6 left-align">{{ balances_start }}</div>

    <div class="col s6 right-align">Deposits:</div>
    <div class="col s6 left-align">{{ deposits }}</div>

    <div class="col s6 right-align">Net Sales:</div>
    <div class="col s6 left-align">{{ net_sales }}</div>

    <div class="col s6 right-align">Balances {{ date_end }}:</div>
    <div class="col s6 left-align">{{ balances_end }}</div>

    <div class="col s6 right-align">Change in balances:</div>
    <div class="col s6 left-align">{{ balances_change }}</div>
  </div>
  <hr>
  <div class="row section center-align">
    <a class="btn waves-effect waves-light" href={% url "index" %}><span>Front page</span></a>
  </div>

  <script>
    $(document).ready(function(){
      $('.datepicker').datepicker(
        autoClose: true
        format: 'yyyy-mm-dd'
      );
    });
  </script>
{% endblock body %}

namu/templates/namu/topup.html
{% extends 'namu/base.html' %}

{% block body %}

  <div class="row section">
    <div class="col s6 offset-s3">
      <h3>Namukilke</h3>
      <div class="divider"></div>
      <h5>{{ user.name }}</h5>
      <h6>Account balance: {{ user.account_balance }} €</h6>
    </div>
  </div>
  <div class="row">
    <div class="col s6 right-align">
      <a class="waves-effect waves-light btn-large" href={% url "index" %}><span>Sign out</span></a>
    </div>
    <div class="col s6 left-align">
      <a class="waves-effect waves-light btn-large" href={% url "buy" user.id %}><span>Buy snacks</span></a>
    </div>
  </div>
  <div class="divider"></div>

  <div class="row section">
    <div class="col s12">
      <h5>Add funds to your account</h5>
    </div>
  </div>

  <div class="row">
    <form id="deposit-form" class="col s2 offset-s5 left-align" action={% url "topup" user.id %} method="post">
      <div class="row">
        {% csrf_token %}
        <div class="input-field col s12">
          <p>
            <label>
              <input class="with-gap" name="payment_method" type="radio" value="m" checked />
              <span>MobilePay</span>
            </label>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <label for="amount">Amount: </label>
          <input name="amount" id="amount" type="number" step="0.01" min="0" placeholder="0" required>
        </div>
        <div class="input-field">
          <button class="btn-large waves-effect waves-light" type="submit"><span>Continue</span></button>
        </div>
      </div>
    </form>
  </div>
  <div class="divider"></div>

  <div id="deposit-modal" class="modal">
    <div class="modal-content">
      <h4>Make a deposit</h4>
      <p>
        Amount: <span id="modal-amount"></span> €
      </p>
      <p id="mobilepay"></p>
      <p id="deposit-modal-text"></p>
      <br>
      <div class="row center-align">
        <div class="col s6 right-align">
          <button class="btn waves-effect waves-light modal-close red darken-2">Cancel</button>
        </div>
        <div class="col s6 left-align">
          <button class="btn waves-effect waves-light modal-close" onclick="postDepositForm()">Done</button>
        </div>
      </div>
    </div>
  </div>
  <!--- Display modal to confirm deposit and give instructions for actual payment. -->
  <script>
    $( "#deposit-form" ).submit(function( event ) {
      event.preventDefault();
      var paymentMethod = $("input[name=payment_method]:checked").val();
      var amount = $("#amount").val();
      showModal(paymentMethod, amount);
    });

    function showModal(paymentMethod, amount) {
      if (paymentMethod === "c") {
        $("#modal-pmethod").html("Cash");
        $("#deposit-modal-text").html("Put cash in the grey box.")
      } else if (paymentMethod === "m") {
        $("#modal-pmethod").html("MobilePay");
        var mp = "Number: {{ namuseta.mobilepay }}"
        $("#mobilepay").html(mp)
        $("#deposit-modal-text").html("Send money with MobilePay to the above number.")
      }
      $("#modal-amount").html(amount);
      $('#deposit-modal').modal();
      $('#deposit-modal').modal('open');
    };

    function postDepositForm() {
      $("#deposit-form").off("submit");
      $("#deposit-form").submit();
    };
  </script>

{% endblock body %}